/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.EventoEscovarDentes;

/**
 *
 * @author Igor Ribeiro
 */
public class TelaEscovarDentes extends javax.swing.JFrame {
    
    MinutoEscovar minutoescovar;
    SegundoEscovar segundoescovar;
    MilesimoEscovar milesimoescovar;
    
    Thread tMinEscovar, tSegEscovar, tMilEscovar;
    
    private int maxTimeInMinutes; 

    /**
     * Creates new form EscovarDentes
     */
    public TelaEscovarDentes() {
        initComponents();
        maxTimeInMinutes = 5;
        resetCountersAndThreads();
        
        minutoescovar = new MinutoEscovar();
        tMinEscovar = new Thread (minutoescovar);
        
        segundoescovar = new SegundoEscovar();
        tSegEscovar = new Thread (segundoescovar);
        
        milesimoescovar = new MilesimoEscovar();
        tMilEscovar = new Thread (milesimoescovar);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtMinEscovar = new javax.swing.JTextField();
        txtSegEscovar = new javax.swing.JTextField();
        txtMilEscovar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 60, 120));

        jButton1.setText("Começar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Parar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Redefinir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtMinEscovar.setText("0");
        txtMinEscovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinEscovarActionPerformed(evt);
            }
        });

        txtSegEscovar.setText("0");

        txtMilEscovar.setText("0");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escova__1_-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMinEscovar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtSegEscovar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMilEscovar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegEscovar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinEscovar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMilEscovar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMinEscovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinEscovarActionPerformed
        // TODO add your handling code here:
        if(!tMinEscovar.isAlive());
        tMinEscovar.start();
        if(!tSegEscovar.isAlive());
        tSegEscovar.start();
        if(!tMilEscovar.isAlive());
        tMilEscovar.start();
        resetCountersAndThreads();
    }//GEN-LAST:event_txtMinEscovarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        minutoescovar.stop();
        segundoescovar.stop();
        milesimoescovar.stop();
        checkMaxTimeExceeded();
        stopCounters();
        } catch (Exception ex) {
           ex.printStackTrace(); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!tMinEscovar.isAlive());
        tMinEscovar.start();
        if(!tSegEscovar.isAlive());
        tSegEscovar.start();
        if(!tMilEscovar.isAlive());
        tMilEscovar.start();
         startCounters();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtMinEscovar.setText("0");
        txtSegEscovar.setText("0");
        txtMilEscovar.setText("0");
        resetCountersAndThreads();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscovarDentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscovarDentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscovarDentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscovarDentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscovarDentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtMilEscovar;
    public static javax.swing.JTextField txtMinEscovar;
    public static javax.swing.JTextField txtSegEscovar;
    // End of variables declaration//GEN-END:variables

    private void checkMaxTimeExceeded() {
        int minutes = Integer.parseInt(txtMinEscovar.getText());
        int segunds = Integer.parseInt(txtSegEscovar.getText());
        int totalTimeInSeconds = minutes * 5 + minutes;

        if (totalTimeInSeconds > maxTimeInMinutes) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tempo de escovação ultrapassado!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Tempo de escovação dentro do limite.");
        }
    }

    private void resetCountersAndThreads() {
       stopCounters();
        txtMinEscovar.setText("0");
        txtSegEscovar.setText("0");
        txtMilEscovar.setText("0");
        initCountersAndThreads();
    }


    private void startCounters() {
       if (!tMinEscovar.isAlive()) tMinEscovar.start();
        if (!tSegEscovar.isAlive()) tSegEscovar.start();
        if (!tMilEscovar.isAlive()) tMilEscovar.start();

    }

    private void stopCounters() {
        if (tMinEscovar!= null && tMinEscovar.isAlive()) tMinEscovar.interrupt();
        if (tSegEscovar != null && tSegEscovar.isAlive()) tSegEscovar.interrupt();
        if (tMilEscovar != null && tMilEscovar.isAlive()) tMilEscovar.interrupt();
    }

    private void initCountersAndThreads() {
        minutoescovar = new MinutoEscovar();
        segundoescovar = new SegundoEscovar();
        milesimoescovar = new MilesimoEscovar();

        tMinEscovar = new Thread(minutoescovar);
        tSegEscovar = new Thread(segundoescovar);
        tMilEscovar = new Thread(milesimoescovar);
    }

    
    
    }

